package com.phamtunglam.lamity.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Indigo-based Material 3 palette; light/dark role pairs.

internal val LightPrimary = Color(0xFF4355B9)
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFDEE0FF)
internal val LightOnPrimaryContainer = Color(0xFF00105C)
internal val LightSecondary = Color(0xFF5B5D72)
internal val LightOnSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFE0E1F9)
internal val LightOnSecondaryContainer = Color(0xFF181A2C)
internal val LightTertiary = Color(0xFF77536D)
internal val LightTertiaryContainer = Color(0xFFFFD7F1)
internal val LightOnTertiaryContainer = Color(0xFF2C1228)
internal val LightSurface = Color(0xFFFBF8FF)
internal val LightOnSurface = Color(0xFF1B1B21)
internal val LightSurfaceVariant = Color(0xFFE3E1EC)
internal val LightOnSurfaceVariant = Color(0xFF46464F)
internal val LightError = Color(0xFFBA1A1A)
internal val LightErrorContainer = Color(0xFFFFDAD6)
internal val LightOnErrorContainer = Color(0xFF410002)
internal val LightOutline = Color(0xFF767680)

internal val DarkPrimary = Color(0xFFBAC3FF)
internal val DarkOnPrimary = Color(0xFF08218A)
internal val DarkPrimaryContainer = Color(0xFF293CA0)
internal val DarkOnPrimaryContainer = Color(0xFFDEE0FF)
internal val DarkSecondary = Color(0xFFC4C5DD)
internal val DarkOnSecondary = Color(0xFF2D2F42)
internal val DarkSecondaryContainer = Color(0xFF434659)
internal val DarkOnSecondaryContainer = Color(0xFFE0E1F9)
internal val DarkTertiary = Color(0xFFE6BAD7)
internal val DarkTertiaryContainer = Color(0xFF5D3C55)
internal val DarkOnTertiaryContainer = Color(0xFFFFD7F1)
internal val DarkSurface = Color(0xFF121318)
internal val DarkOnSurface = Color(0xFFE4E1E9)
internal val DarkSurfaceVariant = Color(0xFF46464F)
internal val DarkOnSurfaceVariant = Color(0xFFC7C5D0)
internal val DarkError = Color(0xFFFFB4AB)
internal val DarkErrorContainer = Color(0xFF93000A)
internal val DarkOnErrorContainer = Color(0xFFFFDAD6)
internal val DarkOutline = Color(0xFF90909A)
